'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ridgeway_Cover_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_v1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_v1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coverrequest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coverrequest", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit_v1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_v1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property facultyarea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("facultyarea", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myrequests() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myrequests", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notifications() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notifications", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_Bold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_Bold", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_BoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_BoldItalic", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_ExtraBold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_ExtraBold", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_ExtraBoldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_ExtraBoldItalic", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_Italic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_Italic", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_Light() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_Light", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_LightItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_LightItalic", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_Regular() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_Regular", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_Semibold() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_Semibold", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property OpenSans_SemiboldItalic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenSans_SemiboldItalic", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property power() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("power", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property roomchange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("roomchange", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property schoollogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("schoollogo", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property schoollogoicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("schoollogoicon", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property trayicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("trayicon", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property userdetails() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userdetails", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property userinterface() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userinterface", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
